name: soundcoop
channels:
  - default
  - conda-forge
dependencies:
  - dask
  - hvplot
  - geopandas
  - geoviews
  - ipykernel
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - python=3.9
  - rioxarray
  - shapely
  - xarray
